import logging
from slack_bolt.async_app import AsyncApp
from slack_sdk.errors import SlackApiError

from backend.app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

# Initialize the Bolt AsyncApp
slack_app = AsyncApp(
    token=settings.SLACK_BOT_TOKEN or "xoxb-dummy-token",
    signing_secret=settings.SLACK_SIGNING_SECRET or "dummy-secret"
)

class SlackClient:
    """Slack Bot API client for sending messages and handling conversations."""

    def __init__(self) -> None:
        self.client = slack_app.client

    async def send_message(self, channel: str, text: str, blocks: list = None) -> bool:
        """Send a message to a Slack channel or DM."""
        try:
            await self.client.chat_postMessage(channel=channel, text=text, blocks=blocks)
            return True
        except SlackApiError as e:
            logger.error(f"Error sending message: {e.response['error']}")
            return False

    async def send_reply(self, channel: str, thread_ts: str, text: str, blocks: list = None) -> bool:
        """Reply in a Slack thread."""
        try:
            await self.client.chat_postMessage(
                channel=channel,
                thread_ts=thread_ts,
                text=text,
                blocks=blocks
            )
            return True
        except SlackApiError as e:
            logger.error(f"Error sending reply: {e.response['error']}")
            return False

    def format_cfo_response_block(self, text: str) -> list:
        """Format the CFO answer in a block kit structure."""
        return [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": text
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "🤖 _Generated by Flowytics AI CFO_"
                    }
                ]
            }
        ]

    def format_proactive_alert_block(self, alert_text: str, severity: str = "warning") -> list:
        """Format an alert message using Block Kit."""
        emoji = "⚠️" if severity == "warning" else "🚨"
        return [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{emoji} Flowytics CFO Alert"
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": alert_text
                }
            }
        ]

    def format_monthly_cfo_report_block(self, metrics: dict, executive_summary: str, key_consideration: str, tenant_name: str = "Your Startup") -> list:
        """Format the highly structured end of month CFO report."""
        
        mrr_str = f"${metrics['mrr']:,.0f}" if metrics.get('mrr') else "N/A"
        burn_str = f"${metrics['net_burn']:,.0f}" if metrics.get('net_burn') else "N/A"
        growth_str = f"{metrics['mrr_growth']}%" if metrics.get('mrr_growth') else "N/A"
        
        return [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📈 Monthly CFO Report: {tenant_name}",
                    "emoji": True
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Executive Summary*\n{executive_summary}"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Net Burn:*\n{burn_str}/mo"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Runway:*\n{metrics['runway_months']} months"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*MRR / Growth:*\n{mrr_str} ({growth_str})"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Cash Balance:*\n${metrics['cash_balance']:,.0f}"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"🎯 *Key Consideration:*\n{key_consideration}"
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "🤖 _Generated by Flowytics AI CFO_"
                    }
                ]
            }
        ]
